// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $('#home').on('click', function() {
      return $('#main').animate({
        left: '+=200'
      });
    });
  });

}).call(this);
